theme: jekyll-theme-cayman
title: Welcome to Shuchen Weng(翁书晨)'s Homepage!
description: I am currently pursuing the Ph.D. degree with the Camera Intelligence Group, Peking University, under the supervision of Prof. Boxin Shi.
