theme: jekyll-theme-cayman
title: Welcome to Shuchen Weng (翁书晨)'s Homepage!
description: I am currently technical staff in Beijing Academy of Artificial Intelligence (BAAI), interested in controllable video generation/editing.
